fix: add NPM_TOKEN verification step in changesets workflow

diff --git a/.github/workflows/changesets.yml b/.github/workflows/changesets.yml
--- a/.github/workflows/changesets.yml
+++ b/.github/workflows/changesets.yml
@@ -8,12 +8,19 @@ on:
 concurrency: ${{ github.workflow }}-${{ github.ref }}
 env:
   CI: true
-
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
 jobs:
   version:
     timeout-minutes: 15
     runs-on: ubuntu-latest
     steps:
+      - name: Verify NPM_TOKEN
+        run: |
+          if [ -z "$NPM_TOKEN" ]; then
+            echo "Error: NPM_TOKEN is not set."
+            exit 1
+          fi
       - name: Checkout code repository
         uses: actions/checkout@v4
 
@@ -44,6 +51,3 @@ jobs:
           commit: "chore: update versions"
           title: "chore: update versions"
           publish: pnpm ci:publish
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
